// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJx8TC_bL-g6RTqH-YEWsKrcPpXMDtslY',
    appId: '1:652028603500:web:03084d3187449b0e60bc49',
    messagingSenderId: '652028603500',
    projectId: 'medquest-3bfe2',
    authDomain: 'medquest-3bfe2.firebaseapp.com',
    storageBucket: 'medquest-3bfe2.firebasestorage.app',
    measurementId: 'G-CBV1Q39ZR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3TCUsHytJ-DCD8sKDyylJp3nP1F3WBbM',
    appId: '1:652028603500:android:1ee05d2b41b25a8860bc49',
    messagingSenderId: '652028603500',
    projectId: 'medquest-3bfe2',
    storageBucket: 'medquest-3bfe2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsrA8_k89CNaKvzvzF4uL_18k5U_CRh9s',
    appId: '1:652028603500:ios:f0258362a8ab490f60bc49',
    messagingSenderId: '652028603500',
    projectId: 'medquest-3bfe2',
    storageBucket: 'medquest-3bfe2.firebasestorage.app',
    iosBundleId: 'com.example.medquest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsrA8_k89CNaKvzvzF4uL_18k5U_CRh9s',
    appId: '1:652028603500:ios:f0258362a8ab490f60bc49',
    messagingSenderId: '652028603500',
    projectId: 'medquest-3bfe2',
    storageBucket: 'medquest-3bfe2.firebasestorage.app',
    iosBundleId: 'com.example.medquest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJx8TC_bL-g6RTqH-YEWsKrcPpXMDtslY',
    appId: '1:652028603500:web:56ed7f26b2afa30a60bc49',
    messagingSenderId: '652028603500',
    projectId: 'medquest-3bfe2',
    authDomain: 'medquest-3bfe2.firebaseapp.com',
    storageBucket: 'medquest-3bfe2.firebasestorage.app',
    measurementId: 'G-H3C73YLCFS',
  );
}
